name: Build and Deploy 
permissions:
  contents: write
on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract new payload
        run: |
          payload='${{toJson(github.event.client_payload)}}'
          echo "$payload" > payload.json
          
      - name: Generate image template
        run: |
          pip uninstall pillow
          pip install Pillow
          python3 main.py          

      - name: Push artifact
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: generated
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "image generated"
      
      - name: Trigger FB hook
        uses: fjogeleit/http-request-action@v1
        id: myRequest        
        with:
          url: ${{ secrets.FB_TRIGGER_ENDPOINT }}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"secret": "${{ secrets.FB_TRIGGER_SECRET }}", "url": "https://raw.githubusercontent.com/jd-dev/gasnoti-poster-maker/generated/poster.png", "message": "gas price update!"}'

      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.headers }}
          
